-- MySQL Script generated by MySQL Workbench
-- Tue May 16 11:42:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema u693453499_turno
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `u693453499_turno` ;

-- -----------------------------------------------------
-- Schema u693453499_turno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u693453499_turno` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema esmiturno
-- -----------------------------------------------------
USE `u693453499_turno` ;

-- -----------------------------------------------------
-- Table `u693453499_turno`.`emt_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u693453499_turno`.`emt_address` (
  `id_emt_address` INT NOT NULL AUTO_INCREMENT,
  `country_code` SMALLINT(3) NULL,
  `country` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  `locality` VARCHAR(45) NULL,
  `latitud` VARCHAR(255) NULL,
  `longitud` VARCHAR(255) NULL,
  `custom` VARCHAR(45) NULL,
  `postal_code` SMALLINT(8) NULL,
  `street_name` VARCHAR(45) NULL,
  `street_number` VARCHAR(45) NULL,
  `tower` VARCHAR(45) NULL,
  `floor` VARCHAR(45) NULL,
  `dpto` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `status` VARCHAR(7) NOT NULL DEFAULT 'OK',
  `comments` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NULL,
  `create_user` VARCHAR(45) NULL,
  `modify_user` VARCHAR(45) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_emt_address`));


-- -----------------------------------------------------
-- Table `u693453499_turno`.`emt_meetplaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u693453499_turno`.`emt_meetplaces` (
  `id_emt_meetplaces` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `fantasy_name` VARCHAR(255) NULL,
  `status` VARCHAR(7) NOT NULL DEFAULT 'OK',
  `comments` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NULL,
  `create_user` VARCHAR(45) NULL,
  `modify_user` VARCHAR(45) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `fk_id_emt_address` INT NOT NULL,
  PRIMARY KEY (`id_emt_meetplaces`, `fk_id_emt_address`),
  INDEX `fk_emt_meetplace_emt_address1_idx` (`fk_id_emt_address` ASC),
  CONSTRAINT `fk_emt_meetplace_emt_address1`
    FOREIGN KEY (`fk_id_emt_address`)
    REFERENCES `u693453499_turno`.`emt_address` (`id_emt_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `u693453499_turno`.`emt_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u693453499_turno`.`emt_contacts` (
  `id_emt_contacts` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `email2` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `intern` VARCHAR(45) NULL,
  `telephone2` VARCHAR(45) NULL,
  `cellphone` VARCHAR(45) NULL,
  `cellphone2` VARCHAR(45) NULL,
  `facebook` VARCHAR(100) NULL,
  `url_site` VARCHAR(45) NULL,
  `status` VARCHAR(7) NOT NULL DEFAULT 'OK',
  `comments` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NULL,
  `create_user` VARCHAR(45) NULL,
  `modify_user` VARCHAR(45) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `fk_id_emt_meetplaces` INT NULL,
  PRIMARY KEY (`id_emt_contacts`),
  UNIQUE INDEX `telephone_UNIQUE` (`telephone` ASC),
  INDEX `fk_emt_contacts_emt_meetplace1_idx` (`fk_id_emt_meetplaces` ASC),
  CONSTRAINT `fk_emt_contacts_emt_meetplace1`
    FOREIGN KEY (`fk_id_emt_meetplaces`)
    REFERENCES `u693453499_turno`.`emt_meetplaces` (`id_emt_meetplaces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `u693453499_turno`.`emt_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u693453499_turno`.`emt_customers` (
  `id_emt_customers` INT NOT NULL AUTO_INCREMENT,
  `dots` INT NOT NULL,
  `status` VARCHAR(7) NOT NULL DEFAULT 'OK',
  `comments` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NULL,
  `create_user` VARCHAR(45) NULL,
  `modify_user` VARCHAR(45) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_emt_customers`));


-- -----------------------------------------------------
-- Table `u693453499_turno`.`emt_providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u693453499_turno`.`emt_providers` (
  `id_emt_providers` INT NOT NULL AUTO_INCREMENT,
  `dots` VARCHAR(45) NULL,
  `status` VARCHAR(7) NOT NULL DEFAULT 'OK',
  `comments` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NULL,
  `create_user` VARCHAR(45) NULL,
  `modify_user` VARCHAR(45) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_emt_providers`));


-- -----------------------------------------------------
-- Table `u693453499_turno`.`emt_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u693453499_turno`.`emt_users` (
  `id_emt_users` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `status` VARCHAR(7) NOT NULL DEFAULT 'OK',
  `comments` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NULL,
  `create_user` VARCHAR(45) NULL,
  `modify_user` VARCHAR(45) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `fk_id_emt_customers` INT NULL,
  `fk_id_emt_providers` INT NULL,
  PRIMARY KEY (`id_emt_users`),
  INDEX `fk_emt_users_emt_customers1_idx` (`fk_id_emt_customers` ASC),
  INDEX `fk_emt_users_emt_providers1_idx` (`fk_id_emt_providers` ASC),
  UNIQUE INDEX `fk_id_emt_customers_UNIQUE` (`fk_id_emt_customers` ASC),
  UNIQUE INDEX `fk_id_emt_providers_UNIQUE` (`fk_id_emt_providers` ASC),
  CONSTRAINT `fk_emt_users_emt_customers1`
    FOREIGN KEY (`fk_id_emt_customers`)
    REFERENCES `u693453499_turno`.`emt_customers` (`id_emt_customers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emt_users_emt_providers1`
    FOREIGN KEY (`fk_id_emt_providers`)
    REFERENCES `u693453499_turno`.`emt_providers` (`id_emt_providers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `u693453499_turno`.`emt_persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u693453499_turno`.`emt_persons` (
  `id_emt_persons` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `document_number` DECIMAL(8) NOT NULL,
  `document_text` VARCHAR(45) NULL,
  `document_type` VARCHAR(10) NOT NULL,
  `nacionality` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `status` VARCHAR(7) NOT NULL DEFAULT 'OK',
  `comments` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NULL,
  `create_user` VARCHAR(45) NULL,
  `modify_user` VARCHAR(45) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `fk_id_emt_address` INT NOT NULL,
  `fk_id_emt_contacts` INT NOT NULL,
  `fk_id_emt_users` INT NOT NULL,
  PRIMARY KEY (`id_emt_persons`, `fk_id_emt_address`, `fk_id_emt_contacts`, `fk_id_emt_users`),
  UNIQUE INDEX `document_UNIQUE` (`document_number` ASC),
  INDEX `fk_emt_persons_emt_address_idx` (`fk_id_emt_address` ASC),
  INDEX `fk_emt_persons_emt_contacts1_idx` (`fk_id_emt_contacts` ASC),
  INDEX `fk_emt_persons_emt_users1_idx` (`fk_id_emt_users` ASC),
  CONSTRAINT `fk_emt_persons_emt_address`
    FOREIGN KEY (`fk_id_emt_address`)
    REFERENCES `u693453499_turno`.`emt_address` (`id_emt_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emt_persons_emt_contacts1`
    FOREIGN KEY (`fk_id_emt_contacts`)
    REFERENCES `u693453499_turno`.`emt_contacts` (`id_emt_contacts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emt_persons_emt_users1`
    FOREIGN KEY (`fk_id_emt_users`)
    REFERENCES `u693453499_turno`.`emt_users` (`id_emt_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `u693453499_turno`.`emt_meets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u693453499_turno`.`emt_meets` (
  `id_emt_meets` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NULL,
  `status` VARCHAR(7) NOT NULL DEFAULT 'OK',
  `comments` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NULL,
  `create_user` VARCHAR(45) NULL,
  `modify_user` VARCHAR(45) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `fk_id_emt_customers` INT NOT NULL,
  `fk_id_emt_providers` INT NOT NULL,
  `fk_id_emt_meetplaces` INT NOT NULL,
  PRIMARY KEY (`id_emt_meets`, `fk_id_emt_customers`, `fk_id_emt_providers`, `fk_id_emt_meetplaces`),
  INDEX `fk_emt_turnos_emt_customers1_idx` (`fk_id_emt_customers` ASC),
  INDEX `fk_emt_turnos_emt_providers1_idx` (`fk_id_emt_providers` ASC),
  INDEX `fk_emt_meet_emt_meetplace1_idx` (`fk_id_emt_meetplaces` ASC),
  CONSTRAINT `fk_emt_turnos_emt_customers1`
    FOREIGN KEY (`fk_id_emt_customers`)
    REFERENCES `u693453499_turno`.`emt_customers` (`id_emt_customers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emt_turnos_emt_providers1`
    FOREIGN KEY (`fk_id_emt_providers`)
    REFERENCES `u693453499_turno`.`emt_providers` (`id_emt_providers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emt_meet_emt_meetplace1`
    FOREIGN KEY (`fk_id_emt_meetplaces`)
    REFERENCES `u693453499_turno`.`emt_meetplaces` (`id_emt_meetplaces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
